import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'nv-green': '#76b900',
        'nv-green-dark': '#5a8d00',
        'nv-green-pale': '#bff230',
        'nv-dark': '#000000',
        'nv-elevated': '#1a1a1a',
        'nv-canvas': '#ffffff',
        'nv-soft': '#f7f7f7',
        'nv-hairline': '#cccccc',
        'nv-hairline-strong': '#5e5e5e',
        'nv-ink': '#000000',
        'nv-body': '#1a1a1a',
        'nv-mute': '#757575',
        'nv-stone': '#898989',
        'nv-ash': '#a7a7a7',
        'nv-on-dark': '#ffffff',
        'nv-error': '#e52020',
        'nv-warning': '#df6500',
        'nv-success': '#3f8500',
        'nv-link': '#0046a4',
        'trigger-safe': '#3f8500',
        'trigger-watch': '#df6500',
        'trigger-breach': '#e52020',
        'trigger-na': '#898989',
      },
      fontFamily: { sans: ['Inter', 'Arial', 'Helvetica', 'sans-serif'] },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.25', fontWeight: '700' }],
        'display-lg': ['36px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-xl': ['24px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-lg': ['22px', { lineHeight: '1.75', fontWeight: '400' }],
        'heading-md': ['20px', { lineHeight: '1.25', fontWeight: '700' }],
        'heading-sm': ['18px', { lineHeight: '1.4', fontWeight: '700' }],
        'card-title': ['17px', { lineHeight: '1.47', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '700' }],
        'body-sm': ['15px', { lineHeight: '1.67', fontWeight: '400' }],
        'btn-lg': ['18px', { lineHeight: '1.25', fontWeight: '700' }],
        'btn-md': ['16px', { lineHeight: '1.25', fontWeight: '700' }],
        'btn-sm': ['14.4px', { lineHeight: '1', fontWeight: '700' }],
        'caption-md': ['14px', { lineHeight: '1.43', fontWeight: '700' }],
        'caption-sm': ['12px', { lineHeight: '1.25', fontWeight: '400' }],
        'utility-xs': ['10px', { lineHeight: '1.5', fontWeight: '700' }],
      },
      borderRadius: { DEFAULT: '2px', sm: '2px', full: '9999px' },
      spacing: { section: '64px' },
      maxWidth: { content: '1280px' },
      boxShadow: { sticky: '0 0 5px 0 rgba(0,0,0,0.3)', none: 'none' },
    },
  },
  plugins: [],
}

export default config
