import { evaluateAllTriggers } from '@/lib/engine/triggerEngine'
import type { Deal } from '@/lib/types/deal'
import type { PerformanceSnapshot } from '@/lib/types/performance'
import type {
  ExtractionStatus,
  TriggerConsequence,
  TriggerEvaluation,
  TriggerFamily,
  TriggerOperator,
  TriggerRule,
} from '@/lib/types/trigger'
import type { Database } from '@/lib/supabase/types'

export const DEMO_DEAL_ID = 'a1b2c3d4-0000-0000-0000-ce47e53a4a2e'
export const VANTAGE_DEAL_ID = 'a1b2c3d4-0000-0000-0001-ce47e53a4a2e'
export const ALIGNED_DEAL_ID = 'a1b2c3d4-0000-0000-0002-ce47e53a4a2e'
export const SWITCH_DEAL_ID = 'a1b2c3d4-0000-0000-0003-ce47e53a4a2e'
export const STACK_DEAL_ID = 'a1b2c3d4-0000-0000-0004-ce47e53a4a2e'

const now = '2026-01-15T00:00:00.000Z'

export const demoDeals: Deal[] = [
  {
    id: DEMO_DEAL_ID,
    userId: null,
    name: 'Centersquare Issuer LLC, Series 2025-2',
    issuer: 'Centersquare Investment Management',
    market: 'NORTHERN_VIRGINIA',
    closingDate: '2025-03-15',
    arDate: '2029-10-15',
    totalIssuance: 940_000_000,
    assetCount: 26,
    collateralDescription: '26 colocation data centers across 10 U.S. markets, about 485 MW total capacity',
    ratingAgency: 'KBRA',
    rating: 'A- (sf)',
    ltv: 0.61,
    isDemo: true,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: VANTAGE_DEAL_ID,
    userId: null,
    name: 'Vantage Data Centers Issuer LLC, Series 2025-1',
    issuer: 'Vantage Data Centers',
    market: 'SILICON_VALLEY',
    closingDate: '2025-02-20',
    arDate: '2030-02-15',
    totalIssuance: 1_350_000_000,
    assetCount: 12,
    collateralDescription: '12 wholesale data centers anchored in Santa Clara and Quincy, about 620 MW total capacity',
    ratingAgency: 'KBRA',
    rating: 'A- (sf)',
    ltv: 0.58,
    isDemo: true,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: ALIGNED_DEAL_ID,
    userId: null,
    name: 'Aligned Data Centers Issuer LLC, Series 2025-1',
    issuer: 'Aligned Data Centers',
    market: 'DALLAS',
    closingDate: '2025-05-10',
    arDate: '2030-05-12',
    totalIssuance: 1_050_000_000,
    assetCount: 9,
    collateralDescription: '9 build-to-scale data centers concentrated in Dallas and Salt Lake City, about 510 MW total capacity',
    ratingAgency: 'KBRA',
    rating: 'A (sf)',
    ltv: 0.6,
    isDemo: true,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: SWITCH_DEAL_ID,
    userId: null,
    name: 'Switch ABS Issuer LLC, Series 2025-2',
    issuer: 'Switch Inc.',
    market: 'PHOENIX',
    closingDate: '2025-04-18',
    arDate: '2029-04-16',
    totalIssuance: 800_000_000,
    assetCount: 7,
    collateralDescription: '7 hyperscale campuses across the Phoenix and Las Vegas corridors, about 410 MW total capacity',
    ratingAgency: 'KBRA',
    rating: 'A- (sf)',
    ltv: 0.57,
    isDemo: true,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: STACK_DEAL_ID,
    userId: null,
    name: 'Stack Infrastructure Issuer LLC, Series 2025-3',
    issuer: 'Stack Infrastructure',
    market: 'CHICAGO',
    closingDate: '2025-06-25',
    arDate: '2030-06-25',
    totalIssuance: 1_200_000_000,
    assetCount: 14,
    collateralDescription: '14 wholesale data centers anchored in Chicago and Northern Virginia, about 560 MW total capacity',
    ratingAgency: 'S&P',
    rating: 'A- (sf)',
    ltv: 0.62,
    isDemo: true,
    status: 'ACTIVE',
    createdAt: now,
    updatedAt: now,
  },
]

export const demoDeal = demoDeals[0]

interface RuleSpec {
  id: string
  family: TriggerFamily
  name: string
  description: string
  metricKey: string
  operator: TriggerOperator
  threshold: number | null
  thresholdUnit: string
  lookbackPeriods?: number
  consequence: TriggerConsequence
  sectionReference: string
  sourceText: string
  extractionStatus?: ExtractionStatus
  extractionConfidence?: number
  watchBuffer?: number
}

function makeRule(dealId: string, spec: RuleSpec): TriggerRule {
  return {
    id: spec.id,
    dealId,
    family: spec.family,
    name: spec.name,
    description: spec.description,
    metricKey: spec.metricKey,
    operator: spec.operator,
    threshold: spec.threshold,
    thresholdUnit: spec.thresholdUnit,
    lookbackPeriods: spec.lookbackPeriods ?? 1,
    consequence: spec.consequence,
    sectionReference: spec.sectionReference,
    sourceText: spec.sourceText,
    extractionStatus: spec.extractionStatus ?? 'APPROVED',
    extractionConfidence: spec.extractionConfidence ?? 0.9,
    watchBuffer: spec.watchBuffer ?? 0.1,
    active: true,
    createdAt: now,
    updatedAt: now,
  }
}

const centersquareRules: TriggerRule[] = [
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000001',
    family: 'DSCR_CASH_TRAP',
    name: '3m DSCR Cash Trap',
    description: 'Cash trap if the three-month rolling average DSCR falls below 1.35x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.35,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 3.14(b)(ii)',
    sourceText: 'If the three-month rolling average DSCR falls below 1.35x, a Cash Trap Event shall occur.',
    extractionConfidence: 0.97,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000002',
    family: 'DSCR_EARLY_AMORTISATION',
    name: '3m DSCR Early Amortisation',
    description: 'Early amortisation if the three-month rolling average DSCR falls below 1.10x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.1,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'EARLY_AMORTISATION',
    sectionReference: 'Section 3.14(c)(i)',
    sourceText: 'If the three-month rolling average DSCR falls below 1.10x, an Early Amortisation Event shall occur.',
    extractionConfidence: 0.96,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000003',
    family: 'LTV_SWEEP',
    name: 'LTV Sweep',
    description: 'Mandatory deleveraging if LTV exceeds 65.0%.',
    metricKey: 'ltv',
    operator: 'GT',
    threshold: 0.65,
    thresholdUnit: '%',
    consequence: 'MANDATORY_DELEVERAGING',
    sectionReference: 'Section 3.15(a)',
    sourceText: 'If the LTV Ratio exceeds 65.0%, excess funds apply to mandatory deleveraging.',
    extractionConfidence: 0.94,
    watchBuffer: 0.08,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000004',
    family: 'OCCUPANCY_RESERVE',
    name: 'Occupancy Reserve',
    description: 'Enhanced liquidity reserve if weighted average occupancy falls below 75.0%.',
    metricKey: 'occupancyRate',
    operator: 'LT',
    threshold: 0.75,
    thresholdUnit: '%',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.16(b)',
    sourceText: 'If weighted average occupancy falls below 75.0%, the issuer shall maintain an Enhanced Liquidity Reserve.',
    extractionConfidence: 0.95,
    watchBuffer: 0.05,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000005',
    family: 'TENANT_CONCENTRATION',
    name: 'Top Tenant Concentration',
    description: 'Enhanced reserve if the largest tenant exceeds 40.0% of contracted revenue.',
    metricKey: 'topTenantRevenuePct',
    operator: 'GT',
    threshold: 0.4,
    thresholdUnit: '%',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.17(a)',
    sourceText: 'Contracted revenue from any single tenant shall not exceed 40.0% of total portfolio revenue.',
    extractionConfidence: 0.91,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000006',
    family: 'WART_RESERVE',
    name: 'WART Covenant',
    description: 'Enhanced reserve if weighted average remaining lease term falls below 2.5 years.',
    metricKey: 'weightedAvgRemainingLeaseTerm',
    operator: 'LT',
    threshold: 2.5,
    thresholdUnit: 'years',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.18',
    sourceText: 'Portfolio weighted average remaining lease term shall be maintained above 2.5 years.',
    extractionConfidence: 0.89,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000007',
    family: 'EXPENSE_RESERVE',
    name: 'Operating Expense Reserve',
    description: 'Enhanced reserve if the operating expense reserve falls below $6.0M.',
    metricKey: 'expenseReserveBalance',
    operator: 'LT',
    threshold: 6_000_000,
    thresholdUnit: 'USD',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.19',
    sourceText: 'The issuer shall maintain an Operating Expense Reserve of at least $6,000,000 at all times.',
    extractionConfidence: 0.9,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000008',
    family: 'ARD_MATURITY',
    name: 'ARD Turbo Test',
    description: 'Turbo amortisation test tied to ARD maturity surveillance.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1,
    thresholdUnit: 'x',
    consequence: 'TURBO_AMORTISATION',
    sectionReference: 'Section 3.20',
    sourceText: 'Additional Notes may only be issued if DSCR pro forma is greater than or equal to 1.35x.',
    extractionConfidence: 0.84,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000009',
    family: 'DSCR_SENIOR_CASH_TRAP',
    name: 'Senior DSCR Cash Trap',
    description: 'Cash trap if the senior DSCR falls below 1.45x.',
    metricKey: 'seniorDscr',
    operator: 'LT',
    threshold: 1.45,
    thresholdUnit: 'x',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 3.14(b)(iv)',
    sourceText: 'If the Senior Debt Service Coverage Ratio falls below 1.45x, a Senior Cash Trap Event shall occur.',
    extractionStatus: 'EXTRACTED',
    extractionConfidence: 0.82,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000010',
    family: 'ADDITIONAL_ISSUANCE',
    name: 'Additional Notes DSCR Condition',
    description: 'Additional notes are blocked unless pro forma DSCR is at least 1.35x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.35,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'ISSUANCE_BLOCKED',
    sectionReference: 'Section 3.21(a)',
    sourceText: 'Additional Notes may only be issued if pro forma DSCR is greater than or equal to 1.35x.',
    extractionConfidence: 0.93,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000011',
    family: 'INTEREST_RESERVE',
    name: 'Senior Interest Reserve Floor',
    description: 'Cash trap if the senior interest reserve falls below $18.0M.',
    metricKey: 'seniorInterestReserveBalance',
    operator: 'LT',
    threshold: 18_000_000,
    thresholdUnit: 'USD',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 3.19(b)',
    sourceText: 'The issuer shall maintain a Senior Interest Reserve Account balance of at least $18,000,000.',
    extractionConfidence: 0.9,
  }),
  makeRule(DEMO_DEAL_ID, {
    id: '11111111-0000-4000-8000-000000000012',
    family: 'PUE_EFFICIENCY',
    name: 'Portfolio PUE Watch',
    description: 'Operational watch if portfolio PUE exceeds 1.38x.',
    metricKey: 'pueRatio',
    operator: 'GT',
    threshold: 1.38,
    thresholdUnit: 'x',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.22',
    sourceText: 'Portfolio power usage effectiveness shall not exceed 1.38x for two consecutive reporting periods.',
    extractionConfidence: 0.85,
  }),
]

const vantageRules: TriggerRule[] = [
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000001',
    family: 'DSCR_CASH_TRAP',
    name: '3m DSCR Cash Trap',
    description: 'Cash trap if the three-month rolling average DSCR falls below 1.30x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.3,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 5.02(a)',
    sourceText: 'A Cash Trap Condition shall exist if the three-month average DSCR is less than 1.30x.',
    extractionConfidence: 0.96,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000002',
    family: 'LTV_SWEEP',
    name: 'LTV Sweep',
    description: 'Mandatory deleveraging if LTV exceeds 70.0%.',
    metricKey: 'ltv',
    operator: 'GT',
    threshold: 0.7,
    thresholdUnit: '%',
    consequence: 'MANDATORY_DELEVERAGING',
    sectionReference: 'Section 5.03',
    sourceText: 'If the Loan-to-Value Ratio exceeds 70.0%, available amounts shall be applied to deleveraging.',
    extractionConfidence: 0.93,
    watchBuffer: 0.08,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000003',
    family: 'OCCUPANCY_RESERVE',
    name: 'Occupancy Reserve',
    description: 'Enhanced reserve if weighted average occupancy falls below 80.0%.',
    metricKey: 'occupancyRate',
    operator: 'LT',
    threshold: 0.8,
    thresholdUnit: '%',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 5.05(b)',
    sourceText: 'If portfolio occupancy falls below 80.0%, an Occupancy Reserve Event shall occur.',
    extractionConfidence: 0.92,
    watchBuffer: 0.05,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000004',
    family: 'INTEREST_RESERVE',
    name: 'Senior Interest Reserve',
    description: 'Cash trap if the senior interest reserve falls below $15.0M.',
    metricKey: 'seniorInterestReserveBalance',
    operator: 'LT',
    threshold: 15_000_000,
    thresholdUnit: 'USD',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 5.06',
    sourceText: 'The issuer shall maintain a Senior Interest Reserve Account balance of at least $15,000,000.',
    extractionConfidence: 0.91,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000005',
    family: 'WALT_CASH_TRAP',
    name: 'WALT Cash Trap',
    description: 'Cash trap if weighted average lease term falls below 3.0 years.',
    metricKey: 'weightedAvgRemainingLeaseTerm',
    operator: 'LT',
    threshold: 3,
    thresholdUnit: 'years',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 5.07',
    sourceText: 'A WALT Trigger Event shall occur if the weighted average lease term is less than 3.0 years.',
    extractionStatus: 'EXTRACTED',
    extractionConfidence: 0.8,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000006',
    family: 'DSCR_EARLY_AMORTISATION',
    name: '3m DSCR Early Amortisation',
    description: 'Early amortisation if the three-month rolling average DSCR falls below 1.15x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.15,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'EARLY_AMORTISATION',
    sectionReference: 'Section 5.02(c)',
    sourceText: 'An Amortization Period shall occur if the three-month average DSCR is less than 1.15x.',
    extractionConfidence: 0.94,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000007',
    family: 'DSCR_SENIOR_CASH_TRAP',
    name: 'PIK Period DSCR Trigger',
    description: 'Class B interest may PIK if senior DSCR falls below 1.45x.',
    metricKey: 'seniorDscr',
    operator: 'LT',
    threshold: 1.45,
    thresholdUnit: 'x',
    consequence: 'RATE_STEP_UP',
    sectionReference: 'Section 5.02(d)',
    sourceText: 'A PIK Period shall be in effect when Senior DSCR is less than 1.45x.',
    extractionConfidence: 0.89,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000008',
    family: 'ADDITIONAL_ISSUANCE',
    name: 'VFN Post-Draw DSCR Condition',
    description: 'Variable-funding note draws are blocked if pro forma DSCR is below 1.80x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.8,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'ISSUANCE_BLOCKED',
    sectionReference: 'Section 5.08(a)',
    sourceText: 'Variable Funding Note draws require pro forma three-month average DSCR of at least 1.80x.',
    extractionConfidence: 0.91,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000009',
    family: 'TENANT_CONCENTRATION',
    name: 'Hyperscaler Concentration Test',
    description: 'Enhanced reserve if the largest tenant exceeds 35.0% of contracted revenue.',
    metricKey: 'topTenantRevenuePct',
    operator: 'GT',
    threshold: 0.35,
    thresholdUnit: '%',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 5.09',
    sourceText: 'No single tenant may represent more than 35.0% of contracted revenue without reserve enhancement.',
    extractionConfidence: 0.88,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000010',
    family: 'PUE_EFFICIENCY',
    name: 'PUE Efficiency Watch',
    description: 'Operational watch if portfolio PUE exceeds 1.34x.',
    metricKey: 'pueRatio',
    operator: 'GT',
    threshold: 1.34,
    thresholdUnit: 'x',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 5.10',
    sourceText: 'Portfolio PUE shall not exceed 1.34x for two consecutive reporting periods.',
    extractionConfidence: 0.83,
  }),
  makeRule(VANTAGE_DEAL_ID, {
    id: '12111111-0000-4000-8000-000000000011',
    family: 'ARD_MATURITY',
    name: 'Post-ARD Turbo Sweep',
    description: 'Turbo amortisation if DSCR is below 1.20x after the anticipated repayment date.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.2,
    thresholdUnit: 'x',
    consequence: 'TURBO_AMORTISATION',
    sectionReference: 'Section 5.12',
    sourceText: 'Following the anticipated repayment date, available funds shall be applied as a turbo sweep if DSCR is below 1.20x.',
    extractionConfidence: 0.87,
  }),
]

const alignedRules: TriggerRule[] = [
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000001',
    family: 'DSCR_CASH_TRAP',
    name: '3m DSCR Cash Trap',
    description: 'Cash trap if the three-month rolling average DSCR falls below 1.25x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.25,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 4.01(c)',
    sourceText: 'A Cash Sweep Period commences if the three-month average DSCR is below 1.25x.',
    extractionConfidence: 0.95,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000002',
    family: 'TENANT_CONCENTRATION',
    name: 'Top Tenant Concentration',
    description: 'Cash trap if the largest tenant exceeds 45.0% of contracted revenue.',
    metricKey: 'topTenantRevenuePct',
    operator: 'GT',
    threshold: 0.45,
    thresholdUnit: '%',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 4.04(a)',
    sourceText: 'If revenue from the largest tenant exceeds 45.0% of contracted revenue, a Concentration Event shall occur.',
    extractionConfidence: 0.9,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000003',
    family: 'WALT_CASH_TRAP',
    name: 'WALT Cash Trap',
    description: 'Cash trap if weighted average lease term falls below 3.0 years.',
    metricKey: 'weightedAvgRemainingLeaseTerm',
    operator: 'LT',
    threshold: 3,
    thresholdUnit: 'years',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 4.05',
    sourceText: 'A WALT Trigger Event shall occur if the portfolio weighted average lease term falls below 3.0 years.',
    extractionConfidence: 0.89,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000004',
    family: 'EXPENSE_RESERVE',
    name: 'Operating Expense Reserve',
    description: 'Cash trap if the operating expense reserve falls below $6.0M.',
    metricKey: 'expenseReserveBalance',
    operator: 'LT',
    threshold: 6_000_000,
    thresholdUnit: 'USD',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 4.06',
    sourceText: 'The issuer shall maintain an Operating Expense Reserve of at least $6,000,000.',
    extractionConfidence: 0.88,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000005',
    family: 'POWER_COST',
    name: 'Power Cost Covenant',
    description: 'Surveillance watch if blended power cost exceeds $0.105/kWh.',
    metricKey: 'powerCostPerKwh',
    operator: 'GT',
    threshold: 0.105,
    thresholdUnit: '$/kWh',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 4.08',
    sourceText: 'A Power Cost Event shall occur if the blended power cost exceeds $0.105 per kWh for any period.',
    extractionStatus: 'EXTRACTED',
    extractionConfidence: 0.78,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000006',
    family: 'DSCR_EARLY_AMORTISATION',
    name: '3m DSCR Early Amortisation',
    description: 'Early amortisation if the three-month rolling average DSCR falls below 1.10x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.1,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'EARLY_AMORTISATION',
    sectionReference: 'Section 4.01(d)',
    sourceText: 'An Early Amortization Event shall occur if the three-month average DSCR is less than 1.10x.',
    extractionConfidence: 0.93,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000007',
    family: 'LTV_SWEEP',
    name: 'Class A LTV Sweep',
    description: 'Mandatory deleveraging if LTV exceeds 67.0%.',
    metricKey: 'ltv',
    operator: 'GT',
    threshold: 0.67,
    thresholdUnit: '%',
    consequence: 'MANDATORY_DELEVERAGING',
    sectionReference: 'Section 4.03',
    sourceText: 'If the Class A LTV Ratio exceeds 67.0%, excess cash flow shall be applied to deleveraging.',
    extractionConfidence: 0.9,
    watchBuffer: 0.08,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000008',
    family: 'ADDITIONAL_ISSUANCE',
    name: 'Additional Issuance LTV Condition',
    description: 'Additional issuance is blocked if pro forma LTV exceeds 70.0%.',
    metricKey: 'ltv',
    operator: 'GT',
    threshold: 0.7,
    thresholdUnit: '%',
    consequence: 'ISSUANCE_BLOCKED',
    sectionReference: 'Section 4.07(a)',
    sourceText: 'Additional issuance requires pro forma LTV not greater than 70.0%.',
    extractionConfidence: 0.91,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000009',
    family: 'OCCUPANCY_RESERVE',
    name: 'Development Ramp Occupancy Test',
    description: 'Enhanced reserve if stabilized occupancy falls below 78.0%.',
    metricKey: 'occupancyRate',
    operator: 'LT',
    threshold: 0.78,
    thresholdUnit: '%',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 4.04(b)',
    sourceText: 'If stabilized portfolio occupancy is less than 78.0%, an Occupancy Reserve Event shall occur.',
    extractionConfidence: 0.9,
    watchBuffer: 0.05,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000010',
    family: 'INTEREST_RESERVE',
    name: 'Senior Interest Reserve Floor',
    description: 'Cash trap if the senior interest reserve falls below $14.0M.',
    metricKey: 'seniorInterestReserveBalance',
    operator: 'LT',
    threshold: 14_000_000,
    thresholdUnit: 'USD',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 4.06(b)',
    sourceText: 'The issuer shall maintain a Senior Interest Reserve Account balance of at least $14,000,000.',
    extractionConfidence: 0.88,
  }),
  makeRule(ALIGNED_DEAL_ID, {
    id: '13111111-0000-4000-8000-000000000011',
    family: 'SERVICER_TERMINATION',
    name: 'Manager Replacement Event',
    description: 'Manager replacement may occur after an uncured reporting or control failure.',
    metricKey: 'tenantCount',
    operator: 'BINARY',
    threshold: null,
    thresholdUnit: 'event',
    consequence: 'MANAGER_REMOVAL',
    sectionReference: 'Section 4.11',
    sourceText: 'An uncured manager reporting failure or control event permits replacement of the manager.',
    extractionStatus: 'EXTRACTED',
    extractionConfidence: 0.73,
  }),
]

const switchRules: TriggerRule[] = [
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000001',
    family: 'DSCR_CASH_TRAP',
    name: '3m DSCR Cash Trap',
    description: 'Cash trap if the three-month rolling average DSCR falls below 1.30x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.3,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 6.01(b)',
    sourceText: 'A Cash Trap Event shall occur if the three-month average DSCR falls below 1.30x.',
    extractionConfidence: 0.95,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000002',
    family: 'PUE_EFFICIENCY',
    name: 'PUE Efficiency Covenant',
    description: 'Surveillance watch if portfolio PUE exceeds 1.40x.',
    metricKey: 'pueRatio',
    operator: 'GT',
    threshold: 1.4,
    thresholdUnit: 'x',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 6.04(a)',
    sourceText: 'The manager shall maintain a portfolio power usage effectiveness no greater than 1.40.',
    extractionConfidence: 0.87,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000003',
    family: 'POWER_COST',
    name: 'Power Cost Covenant',
    description: 'Surveillance watch if blended power cost exceeds $0.095/kWh.',
    metricKey: 'powerCostPerKwh',
    operator: 'GT',
    threshold: 0.095,
    thresholdUnit: '$/kWh',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 6.04(b)',
    sourceText: 'A Power Cost Event shall occur if the blended power cost exceeds $0.095 per kWh.',
    extractionConfidence: 0.86,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000004',
    family: 'OCCUPANCY_RESERVE',
    name: 'Occupancy Reserve',
    description: 'Enhanced reserve if weighted average occupancy falls below 75.0%.',
    metricKey: 'occupancyRate',
    operator: 'LT',
    threshold: 0.75,
    thresholdUnit: '%',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 6.05',
    sourceText: 'If weighted average occupancy falls below 75.0%, an Occupancy Reserve Event shall occur.',
    extractionConfidence: 0.92,
    watchBuffer: 0.05,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000005',
    family: 'INTEREST_RESERVE',
    name: 'Senior Interest Reserve',
    description: 'Cash trap if the senior interest reserve falls below $12.0M.',
    metricKey: 'seniorInterestReserveBalance',
    operator: 'LT',
    threshold: 12_000_000,
    thresholdUnit: 'USD',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 6.06',
    sourceText: 'The issuer shall maintain a Senior Interest Reserve Account balance of at least $12,000,000.',
    extractionStatus: 'EXTRACTED',
    extractionConfidence: 0.81,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000006',
    family: 'DSCR_EARLY_AMORTISATION',
    name: '3m DSCR Early Amortisation',
    description: 'Early amortisation if the three-month rolling average DSCR falls below 1.10x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.1,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'EARLY_AMORTISATION',
    sectionReference: 'Section 6.01(c)',
    sourceText: 'An Early Amortization Event shall occur if the three-month average DSCR is less than 1.10x.',
    extractionConfidence: 0.93,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000007',
    family: 'LTV_SWEEP',
    name: 'Class A LTV Sweep',
    description: 'Mandatory deleveraging if LTV exceeds 66.0%.',
    metricKey: 'ltv',
    operator: 'GT',
    threshold: 0.66,
    thresholdUnit: '%',
    consequence: 'MANDATORY_DELEVERAGING',
    sectionReference: 'Section 6.03',
    sourceText: 'If the Class A LTV Ratio exceeds 66.0%, excess cash flow shall be applied to deleveraging.',
    extractionConfidence: 0.91,
    watchBuffer: 0.08,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000008',
    family: 'ADDITIONAL_ISSUANCE',
    name: 'VFN Post-Draw DSCR Condition',
    description: 'Variable-funding note draws are blocked if pro forma DSCR is below 1.55x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.55,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'ISSUANCE_BLOCKED',
    sectionReference: 'Section 6.08(a)',
    sourceText: 'Variable Funding Note draws require pro forma three-month average DSCR of at least 1.55x.',
    extractionConfidence: 0.9,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000009',
    family: 'TENANT_CONCENTRATION',
    name: 'Anchor Tenant Concentration Test',
    description: 'Enhanced reserve if the largest tenant exceeds 38.0% of contracted revenue.',
    metricKey: 'topTenantRevenuePct',
    operator: 'GT',
    threshold: 0.38,
    thresholdUnit: '%',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 6.07',
    sourceText: 'No single tenant may represent more than 38.0% of contracted revenue without reserve enhancement.',
    extractionConfidence: 0.88,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000010',
    family: 'WALT_CASH_TRAP',
    name: 'WALT Cash Trap',
    description: 'Cash trap if weighted average lease term falls below 3.20 years.',
    metricKey: 'weightedAvgRemainingLeaseTerm',
    operator: 'LT',
    threshold: 3.2,
    thresholdUnit: 'years',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 6.09',
    sourceText: 'A WALT Trigger Event shall occur if the portfolio weighted average lease term falls below 3.20 years.',
    extractionConfidence: 0.86,
  }),
  makeRule(SWITCH_DEAL_ID, {
    id: '14111111-0000-4000-8000-000000000011',
    family: 'ARD_MATURITY',
    name: 'Post-ARD Turbo Sweep',
    description: 'Turbo amortisation if DSCR is below 1.15x after the anticipated repayment date.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.15,
    thresholdUnit: 'x',
    consequence: 'TURBO_AMORTISATION',
    sectionReference: 'Section 6.12',
    sourceText: 'Following the anticipated repayment date, available funds shall be applied as a turbo sweep if DSCR is below 1.15x.',
    extractionConfidence: 0.84,
  }),
]

const stackRules: TriggerRule[] = [
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000001',
    family: 'DSCR_SENIOR_CASH_TRAP',
    name: 'Senior DSCR Cash Trap',
    description: 'Cash trap if the senior DSCR falls below 1.50x.',
    metricKey: 'seniorDscr',
    operator: 'LT',
    threshold: 1.5,
    thresholdUnit: 'x',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 7.02',
    sourceText: 'A Senior Cash Trap Event shall occur if the Senior DSCR is less than 1.50x.',
    extractionConfidence: 0.94,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000002',
    family: 'LTV_SWEEP',
    name: 'LTV Sweep',
    description: 'Mandatory deleveraging if LTV exceeds 68.0%.',
    metricKey: 'ltv',
    operator: 'GT',
    threshold: 0.68,
    thresholdUnit: '%',
    consequence: 'MANDATORY_DELEVERAGING',
    sectionReference: 'Section 7.03',
    sourceText: 'If the LTV Ratio exceeds 68.0%, excess cash flow shall be applied to mandatory deleveraging.',
    extractionConfidence: 0.92,
    watchBuffer: 0.08,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000003',
    family: 'WART_RESERVE',
    name: 'WART Covenant',
    description: 'Enhanced reserve if weighted average remaining lease term falls below 2.5 years.',
    metricKey: 'weightedAvgRemainingLeaseTerm',
    operator: 'LT',
    threshold: 2.5,
    thresholdUnit: 'years',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 7.04',
    sourceText: 'Portfolio weighted average remaining lease term shall be maintained above 2.5 years.',
    extractionConfidence: 0.9,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000004',
    family: 'TENANT_CONCENTRATION',
    name: 'Top Tenant Concentration',
    description: 'Cash trap if the largest tenant exceeds 45.0% of contracted revenue.',
    metricKey: 'topTenantRevenuePct',
    operator: 'GT',
    threshold: 0.45,
    thresholdUnit: '%',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 7.05',
    sourceText: 'If the largest tenant exceeds 45.0% of contracted revenue, a Concentration Event shall occur.',
    extractionConfidence: 0.89,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000005',
    family: 'DSCR_EARLY_AMORTISATION',
    name: '3m DSCR Early Amortisation',
    description: 'Early amortisation if the three-month rolling average DSCR falls below 1.05x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.05,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'EARLY_AMORTISATION',
    sectionReference: 'Section 7.06',
    sourceText: 'An Early Amortisation Event shall occur if the three-month average DSCR falls below 1.05x.',
    extractionStatus: 'EXTRACTED',
    extractionConfidence: 0.79,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000006',
    family: 'DSCR_CASH_TRAP',
    name: '3m DSCR Cash Trap',
    description: 'Cash trap if the three-month rolling average DSCR falls below 1.28x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.28,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 7.02(b)',
    sourceText: 'A Cash Trap Period shall occur if the three-month average DSCR is less than 1.28x.',
    extractionConfidence: 0.93,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000007',
    family: 'ADDITIONAL_ISSUANCE',
    name: 'Additional Issuance LTV Condition',
    description: 'Additional issuance is blocked if pro forma LTV exceeds 68.0%.',
    metricKey: 'ltv',
    operator: 'GT',
    threshold: 0.68,
    thresholdUnit: '%',
    consequence: 'ISSUANCE_BLOCKED',
    sectionReference: 'Section 7.08(a)',
    sourceText: 'Additional issuance requires pro forma LTV not greater than 68.0%.',
    extractionConfidence: 0.9,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000008',
    family: 'OCCUPANCY_RESERVE',
    name: 'Occupancy Reserve',
    description: 'Enhanced reserve if weighted average occupancy falls below 82.0%.',
    metricKey: 'occupancyRate',
    operator: 'LT',
    threshold: 0.82,
    thresholdUnit: '%',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 7.05(b)',
    sourceText: 'If portfolio occupancy falls below 82.0%, an Occupancy Reserve Event shall occur.',
    extractionConfidence: 0.89,
    watchBuffer: 0.05,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000009',
    family: 'INTEREST_RESERVE',
    name: 'Senior Interest Reserve Floor',
    description: 'Cash trap if the senior interest reserve falls below $16.0M.',
    metricKey: 'seniorInterestReserveBalance',
    operator: 'LT',
    threshold: 16_000_000,
    thresholdUnit: 'USD',
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 7.07',
    sourceText: 'The issuer shall maintain a Senior Interest Reserve Account balance of at least $16,000,000.',
    extractionConfidence: 0.88,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000010',
    family: 'PUE_EFFICIENCY',
    name: 'PUE Efficiency Watch',
    description: 'Operational watch if portfolio PUE exceeds 1.36x.',
    metricKey: 'pueRatio',
    operator: 'GT',
    threshold: 1.36,
    thresholdUnit: 'x',
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 7.09',
    sourceText: 'Portfolio PUE shall not exceed 1.36x for two consecutive reporting periods.',
    extractionConfidence: 0.82,
  }),
  makeRule(STACK_DEAL_ID, {
    id: '15111111-0000-4000-8000-000000000011',
    family: 'ARD_MATURITY',
    name: 'Post-ARD Turbo Sweep',
    description: 'Turbo amortisation if DSCR is below 1.15x after the anticipated repayment date.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.15,
    thresholdUnit: 'x',
    consequence: 'TURBO_AMORTISATION',
    sectionReference: 'Section 7.12',
    sourceText: 'Following the anticipated repayment date, available funds shall be applied as a turbo sweep if DSCR is below 1.15x.',
    extractionConfidence: 0.84,
  }),
]

export const demoTriggerRules: TriggerRule[] = [
  ...centersquareRules,
  ...vantageRules,
  ...alignedRules,
  ...switchRules,
  ...stackRules,
]

const PERIOD_DATES = [
  '2025-01-31',
  '2025-02-28',
  '2025-03-31',
  '2025-04-30',
  '2025-05-31',
  '2025-06-30',
  '2025-07-31',
  '2025-08-31',
  '2025-09-30',
  '2025-10-31',
  '2025-11-30',
  '2025-12-31',
]

type DriftableMetric =
  | 'occupancy'
  | 'dscr'
  | 'ltv'
  | 'topTenant'
  | 'wart'
  | 'reserve'
  | 'pue'
  | 'powerCost'

export interface SnapshotProfile {
  idPrefix: string
  totalCapacityMW: number
  scheduledDebtService: number
  seniorDebtService: number
  outstandingStart: number
  monthlyAmortisation: number
  contractedRevenueStart: number
  contractedRevenueDrift: number
  grossRevenueStart: number
  grossRevenueDrift: number
  operatingExpensesStart: number
  operatingExpensesDrift: number
  tenantCountStart: number
  tenantCountDrift: number
  seniorInterestReserveBalance: number
  requiredReserveBalance: number
  start: Record<DriftableMetric, number>
  drift: Record<DriftableMetric, number>
  series?: Partial<Record<DriftableMetric, readonly number[]>>
  notes: string
}

function metricAt(profile: SnapshotProfile, metric: DriftableMetric, index: number) {
  const fromSeries = profile.series?.[metric]?.[index]
  if (typeof fromSeries === 'number') return fromSeries
  return profile.start[metric] + profile.drift[metric] * index
}

function round(value: number, digits: number) {
  const factor = 10 ** digits
  return Math.round(value * factor) / factor
}

export function generateSnapshots(dealId: string, profile: SnapshotProfile): PerformanceSnapshot[] {
  return PERIOD_DATES.map((periodDate, index) => {
    const occupancyRate = round(metricAt(profile, 'occupancy', index), 4)
    const dscr = round(metricAt(profile, 'dscr', index), 4)
    const ltv = round(metricAt(profile, 'ltv', index), 4)
    const topTenantRevenuePct = round(metricAt(profile, 'topTenant', index), 4)
    const weightedAvgRemainingLeaseTerm = round(metricAt(profile, 'wart', index), 2)
    const expenseReserveBalance = Math.round(metricAt(profile, 'reserve', index))
    const pueRatio = round(metricAt(profile, 'pue', index), 3)
    const powerCostPerKwh = round(metricAt(profile, 'powerCost', index), 4)

    const netCashFlow = Math.round(profile.scheduledDebtService * dscr)
    const outstandingBalance = profile.outstandingStart - profile.monthlyAmortisation * index

    return {
      id: `${profile.idPrefix}-0000-4000-8000-${String(index + 1).padStart(12, '0')}`,
      dealId,
      periodDate,
      occupancyRate,
      leasedCapacityMW: round(profile.totalCapacityMW * occupancyRate, 2),
      totalCapacityMW: profile.totalCapacityMW,
      contractedRevenue: Math.round(profile.contractedRevenueStart + profile.contractedRevenueDrift * index),
      grossRevenue: Math.round(profile.grossRevenueStart + profile.grossRevenueDrift * index),
      operatingExpenses: Math.round(profile.operatingExpensesStart + profile.operatingExpensesDrift * index),
      netCashFlow,
      scheduledDebtService: profile.scheduledDebtService,
      seniorDebtService: profile.seniorDebtService,
      dscr,
      seniorDscr: round(netCashFlow / profile.seniorDebtService, 2),
      pueRatio,
      powerCostPerKwh,
      topTenantRevenuePct,
      tenantCount: Math.round(profile.tenantCountStart + profile.tenantCountDrift * index),
      weightedAvgRemainingLeaseTerm,
      outstandingBalance,
      appraisedValue: Math.round(outstandingBalance / ltv),
      ltv,
      seniorInterestReserveBalance: profile.seniorInterestReserveBalance,
      expenseReserveBalance,
      requiredReserveBalance: profile.requiredReserveBalance,
      source: 'DEMO',
      notes: profile.notes,
      createdAt: `${periodDate}T00:00:00.000Z`,
    }
  })
}

// Centersquare keeps the original hand-tuned cash-trap arc (DSCR 1.42x -> 1.14x).
const centersquareProfile: SnapshotProfile = {
  idPrefix: '22222222',
  totalCapacityMW: 485,
  scheduledDebtService: 6_000_000,
  seniorDebtService: 4_800_000,
  outstandingStart: 940_000_000,
  monthlyAmortisation: 5_000_000,
  contractedRevenueStart: 12_000_000,
  contractedRevenueDrift: -90_000,
  grossRevenueStart: 12_300_000,
  grossRevenueDrift: -100_000,
  operatingExpensesStart: 4_000_000,
  operatingExpensesDrift: 35_000,
  tenantCountStart: 42,
  tenantCountDrift: -0.2,
  seniorInterestReserveBalance: 20_000_000,
  requiredReserveBalance: 6_000_000,
  start: { occupancy: 0.87, dscr: 1.42, ltv: 0.59, topTenant: 0.28, wart: 3.2, reserve: 7_800_000, pue: 1.25, powerCost: 0.081 },
  drift: { occupancy: 0, dscr: 0, ltv: 0, topTenant: 0, wart: 0, reserve: 0, pue: 0.003, powerCost: 0.001 },
  series: {
    occupancy: [0.87, 0.87, 0.86, 0.85, 0.83, 0.82, 0.8, 0.78, 0.76, 0.76, 0.76, 0.8],
    dscr: [1.42, 1.41, 1.4, 1.38, 1.37, 1.36, 1.33, 1.32, 1.28, 1.19, 1.16, 1.14],
    ltv: [0.59, 0.59, 0.6, 0.6, 0.6, 0.61, 0.61, 0.61, 0.62, 0.62, 0.62, 0.62],
    topTenant: [0.28, 0.28, 0.29, 0.29, 0.3, 0.3, 0.31, 0.31, 0.32, 0.32, 0.32, 0.32],
    wart: [3.2, 3.17, 3.13, 3.1, 3.06, 3.02, 2.98, 2.94, 2.9, 2.86, 2.83, 2.8],
    reserve: [7_800_000, 7_600_000, 7_450_000, 7_300_000, 7_150_000, 7_050_000, 6_950_000, 6_850_000, 6_700_000, 6_850_000, 6_750_000, 6_700_000],
  },
  notes: 'Synthetic Centersquare monthly surveillance scenario',
}

// Healthy and flat: comfortable headroom on every covenant.
const vantageProfile: SnapshotProfile = {
  idPrefix: '32222222',
  totalCapacityMW: 620,
  scheduledDebtService: 8_200_000,
  seniorDebtService: 6_600_000,
  outstandingStart: 1_350_000_000,
  monthlyAmortisation: 6_000_000,
  contractedRevenueStart: 17_500_000,
  contractedRevenueDrift: 40_000,
  grossRevenueStart: 17_900_000,
  grossRevenueDrift: 40_000,
  operatingExpensesStart: 5_100_000,
  operatingExpensesDrift: 12_000,
  tenantCountStart: 18,
  tenantCountDrift: 0.1,
  seniorInterestReserveBalance: 21_000_000,
  requiredReserveBalance: 8_000_000,
  start: { occupancy: 0.92, dscr: 1.62, ltv: 0.58, topTenant: 0.22, wart: 4.6, reserve: 9_500_000, pue: 1.22, powerCost: 0.078 },
  drift: { occupancy: -0.001, dscr: -0.002, ltv: 0, topTenant: 0.0005, wart: -0.02, reserve: -20_000, pue: 0.001, powerCost: 0.0002 },
  notes: 'Synthetic Vantage monthly surveillance scenario (stable)',
}

// Drifting toward WATCH: DSCR and WALT erode steadily through the year.
const alignedProfile: SnapshotProfile = {
  idPrefix: '42222222',
  totalCapacityMW: 510,
  scheduledDebtService: 7_000_000,
  seniorDebtService: 5_700_000,
  outstandingStart: 1_050_000_000,
  monthlyAmortisation: 4_500_000,
  contractedRevenueStart: 13_800_000,
  contractedRevenueDrift: -60_000,
  grossRevenueStart: 14_100_000,
  grossRevenueDrift: -65_000,
  operatingExpensesStart: 4_400_000,
  operatingExpensesDrift: 30_000,
  tenantCountStart: 11,
  tenantCountDrift: 0,
  seniorInterestReserveBalance: 16_000_000,
  requiredReserveBalance: 6_000_000,
  start: { occupancy: 0.88, dscr: 1.45, ltv: 0.6, topTenant: 0.37, wart: 3.5, reserve: 7_500_000, pue: 1.28, powerCost: 0.089 },
  drift: { occupancy: -0.004, dscr: -0.011, ltv: 0.001, topTenant: 0.005, wart: -0.04, reserve: -60_000, pue: 0.002, powerCost: 0.0008 },
  notes: 'Synthetic Aligned monthly surveillance scenario (deteriorating)',
}

// Recovering: DSCR climbs back while PUE and power cost sit just below their
// covenant thresholds so live Phoenix grid stress pushes them into WATCH.
const switchProfile: SnapshotProfile = {
  idPrefix: '52222222',
  totalCapacityMW: 410,
  scheduledDebtService: 5_400_000,
  seniorDebtService: 4_400_000,
  outstandingStart: 800_000_000,
  monthlyAmortisation: 3_500_000,
  contractedRevenueStart: 10_400_000,
  contractedRevenueDrift: 70_000,
  grossRevenueStart: 10_700_000,
  grossRevenueDrift: 70_000,
  operatingExpensesStart: 3_700_000,
  operatingExpensesDrift: 8_000,
  tenantCountStart: 9,
  tenantCountDrift: 0.1,
  seniorInterestReserveBalance: 14_000_000,
  requiredReserveBalance: 5_000_000,
  start: { occupancy: 0.78, dscr: 1.22, ltv: 0.57, topTenant: 0.33, wart: 3.8, reserve: 6_400_000, pue: 1.34, powerCost: 0.088 },
  drift: { occupancy: 0.008, dscr: 0.018, ltv: -0.001, topTenant: -0.001, wart: 0.01, reserve: 40_000, pue: 0.003, powerCost: 0.0003 },
  notes: 'Synthetic Switch monthly surveillance scenario (recovering)',
}

// Stable senior coverage with modest LTV creep toward its sweep test.
const stackProfile: SnapshotProfile = {
  idPrefix: '62222222',
  totalCapacityMW: 560,
  scheduledDebtService: 7_500_000,
  seniorDebtService: 6_200_000,
  outstandingStart: 1_200_000_000,
  monthlyAmortisation: 5_500_000,
  contractedRevenueStart: 15_200_000,
  contractedRevenueDrift: -20_000,
  grossRevenueStart: 15_600_000,
  grossRevenueDrift: -20_000,
  operatingExpensesStart: 4_900_000,
  operatingExpensesDrift: 20_000,
  tenantCountStart: 24,
  tenantCountDrift: 0,
  seniorInterestReserveBalance: 19_000_000,
  requiredReserveBalance: 7_000_000,
  start: { occupancy: 0.89, dscr: 1.36, ltv: 0.62, topTenant: 0.3, wart: 3.4, reserve: 8_200_000, pue: 1.27, powerCost: 0.083 },
  drift: { occupancy: -0.002, dscr: -0.004, ltv: 0.001, topTenant: 0.001, wart: -0.03, reserve: -30_000, pue: 0.001, powerCost: 0.0004 },
  notes: 'Synthetic Stack monthly surveillance scenario (watch on senior coverage)',
}

export const demoSnapshots: PerformanceSnapshot[] = [
  ...generateSnapshots(DEMO_DEAL_ID, centersquareProfile),
  ...generateSnapshots(VANTAGE_DEAL_ID, vantageProfile),
  ...generateSnapshots(ALIGNED_DEAL_ID, alignedProfile),
  ...generateSnapshots(SWITCH_DEAL_ID, switchProfile),
  ...generateSnapshots(STACK_DEAL_ID, stackProfile),
]

function approvedRulesForDeal(dealId: string) {
  return demoTriggerRules.filter(
    (rule) => rule.dealId === dealId && rule.extractionStatus === 'APPROVED',
  )
}

export function demoEvaluationsForSnapshot(snapshotId: string): TriggerEvaluation[] {
  const snapshot = demoSnapshots.find((item) => item.id === snapshotId) ?? demoSnapshots.at(-1)
  if (!snapshot) return []
  const scopedSnapshots = demoSnapshots.filter(
    (item) => item.dealId === snapshot.dealId && item.periodDate <= snapshot.periodDate,
  )
  return evaluateAllTriggers(approvedRulesForDeal(snapshot.dealId), scopedSnapshots)
}

export const demoEvaluations = demoSnapshots.flatMap((snapshot) =>
  demoEvaluationsForSnapshot(snapshot.id),
)

export function toDealRow(deal: Deal): Database['public']['Tables']['deals']['Insert'] {
  return {
    id: deal.id,
    user_id: deal.userId,
    name: deal.name,
    issuer: deal.issuer,
    market: deal.market,
    closing_date: deal.closingDate,
    ar_date: deal.arDate,
    total_issuance: deal.totalIssuance,
    asset_count: deal.assetCount,
    collateral_description: deal.collateralDescription,
    rating_agency: deal.ratingAgency,
    rating: deal.rating,
    ltv: deal.ltv,
    is_demo: deal.isDemo,
    status: deal.status,
    created_at: deal.createdAt,
    updated_at: deal.updatedAt,
  }
}

export function toTriggerRuleRow(
  rule: TriggerRule,
): Database['public']['Tables']['trigger_rules']['Insert'] {
  return {
    id: rule.id,
    deal_id: rule.dealId,
    family: rule.family,
    name: rule.name,
    description: rule.description,
    metric_key: rule.metricKey,
    operator: rule.operator,
    threshold: rule.threshold,
    threshold_unit: rule.thresholdUnit,
    lookback_periods: rule.lookbackPeriods,
    consequence: rule.consequence,
    section_reference: rule.sectionReference,
    source_text: rule.sourceText,
    extraction_status: rule.extractionStatus,
    extraction_confidence: rule.extractionConfidence,
    watch_buffer: rule.watchBuffer,
    active: rule.active,
    created_at: rule.createdAt,
    updated_at: rule.updatedAt,
  }
}

export function toSnapshotRow(
  snapshot: PerformanceSnapshot,
): Database['public']['Tables']['performance_snapshots']['Insert'] {
  return {
    id: snapshot.id,
    deal_id: snapshot.dealId,
    period_date: snapshot.periodDate,
    occupancy_rate: snapshot.occupancyRate,
    leased_capacity_mw: snapshot.leasedCapacityMW,
    total_capacity_mw: snapshot.totalCapacityMW,
    contracted_revenue: snapshot.contractedRevenue,
    gross_revenue: snapshot.grossRevenue,
    operating_expenses: snapshot.operatingExpenses,
    net_cash_flow: snapshot.netCashFlow,
    scheduled_debt_service: snapshot.scheduledDebtService,
    senior_debt_service: snapshot.seniorDebtService,
    dscr: snapshot.dscr,
    senior_dscr: snapshot.seniorDscr,
    ltv: snapshot.ltv,
    pue_ratio: snapshot.pueRatio,
    power_cost_per_kwh: snapshot.powerCostPerKwh,
    top_tenant_revenue_pct: snapshot.topTenantRevenuePct,
    tenant_count: snapshot.tenantCount,
    weighted_avg_remaining_lease_term: snapshot.weightedAvgRemainingLeaseTerm,
    outstanding_balance: snapshot.outstandingBalance,
    appraised_value: snapshot.appraisedValue,
    senior_interest_reserve_balance: snapshot.seniorInterestReserveBalance,
    expense_reserve_balance: snapshot.expenseReserveBalance,
    required_reserve_balance: snapshot.requiredReserveBalance,
    source: snapshot.source,
    notes: snapshot.notes,
    created_at: snapshot.createdAt,
  }
}

export function toEvaluationRow(
  evaluation: TriggerEvaluation,
): Database['public']['Tables']['trigger_evaluations']['Insert'] {
  return {
    rule_id: evaluation.ruleId,
    snapshot_id: evaluation.snapshotId,
    status: evaluation.status,
    current_value: evaluation.currentValue,
    threshold: evaluation.threshold,
    distance_to_breach_pct: evaluation.distanceToBreachPct,
    lookback_values: evaluation.lookbackValues,
    evaluated_at: evaluation.evaluatedAt,
  }
}
