import { evaluateAllTriggers } from '@/lib/engine/triggerEngine'
import type { Deal } from '@/lib/types/deal'
import type { PerformanceSnapshot } from '@/lib/types/performance'
import type { TriggerEvaluation, TriggerRule } from '@/lib/types/trigger'
import type { Database } from '@/lib/supabase/types'

export const DEMO_DEAL_ID = 'a1b2c3d4-0000-0000-0000-ce47e53a4a2e'

const now = '2026-01-15T00:00:00.000Z'

export const demoDeal: Deal = {
  id: DEMO_DEAL_ID,
  userId: null,
  name: 'Centersquare Issuer LLC, Series 2025-2',
  issuer: 'Centersquare Investment Management',
  closingDate: '2025-03-15',
  arDate: '2029-10-15',
  totalIssuance: 940_000_000,
  assetCount: 26,
  collateralDescription: '26 colocation data centers across 10 U.S. markets, about 485 MW total capacity',
  ratingAgency: 'KBRA',
  rating: 'A- (sf)',
  ltv: 0.61,
  isDemo: true,
  status: 'ACTIVE',
  createdAt: now,
  updatedAt: now,
}

export const demoTriggerRules: TriggerRule[] = [
  {
    id: '11111111-0000-4000-8000-000000000001',
    dealId: DEMO_DEAL_ID,
    family: 'DSCR_CASH_TRAP',
    name: '3m DSCR Cash Trap',
    description: 'Cash trap if the three-month rolling average DSCR falls below 1.35x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.35,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'CASH_TRAP',
    sectionReference: 'Section 3.14(b)(ii)',
    sourceText: 'If the three-month rolling average DSCR falls below 1.35x, a Cash Trap Event shall occur.',
    extractionStatus: 'APPROVED',
    extractionConfidence: 0.97,
    watchBuffer: 0.1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '11111111-0000-4000-8000-000000000002',
    dealId: DEMO_DEAL_ID,
    family: 'DSCR_EARLY_AMORTISATION',
    name: '3m DSCR Early Amortisation',
    description: 'Early amortisation if the three-month rolling average DSCR falls below 1.10x.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1.1,
    thresholdUnit: 'x',
    lookbackPeriods: 3,
    consequence: 'EARLY_AMORTISATION',
    sectionReference: 'Section 3.14(c)(i)',
    sourceText: 'If the three-month rolling average DSCR falls below 1.10x, an Early Amortisation Event shall occur.',
    extractionStatus: 'APPROVED',
    extractionConfidence: 0.96,
    watchBuffer: 0.1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '11111111-0000-4000-8000-000000000003',
    dealId: DEMO_DEAL_ID,
    family: 'LTV_SWEEP',
    name: 'LTV Sweep',
    description: 'Mandatory deleveraging if LTV exceeds 65.0%.',
    metricKey: 'ltv',
    operator: 'GT',
    threshold: 0.65,
    thresholdUnit: '%',
    lookbackPeriods: 1,
    consequence: 'MANDATORY_DELEVERAGING',
    sectionReference: 'Section 3.15(a)',
    sourceText: 'If the LTV Ratio exceeds 65.0%, excess funds apply to mandatory deleveraging.',
    extractionStatus: 'APPROVED',
    extractionConfidence: 0.94,
    watchBuffer: 0.08,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '11111111-0000-4000-8000-000000000004',
    dealId: DEMO_DEAL_ID,
    family: 'OCCUPANCY_RESERVE',
    name: 'Occupancy Reserve',
    description: 'Enhanced liquidity reserve if weighted average occupancy falls below 75.0%.',
    metricKey: 'occupancyRate',
    operator: 'LT',
    threshold: 0.75,
    thresholdUnit: '%',
    lookbackPeriods: 1,
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.16(b)',
    sourceText: 'If weighted average occupancy falls below 75.0%, the issuer shall maintain an Enhanced Liquidity Reserve.',
    extractionStatus: 'APPROVED',
    extractionConfidence: 0.95,
    watchBuffer: 0.05,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '11111111-0000-4000-8000-000000000005',
    dealId: DEMO_DEAL_ID,
    family: 'TENANT_CONCENTRATION',
    name: 'Top Tenant Concentration',
    description: 'Enhanced reserve if the largest tenant exceeds 40.0% of contracted revenue.',
    metricKey: 'topTenantRevenuePct',
    operator: 'GT',
    threshold: 0.4,
    thresholdUnit: '%',
    lookbackPeriods: 1,
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.17(a)',
    sourceText: 'Contracted revenue from any single tenant shall not exceed 40.0% of total portfolio revenue.',
    extractionStatus: 'APPROVED',
    extractionConfidence: 0.91,
    watchBuffer: 0.1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '11111111-0000-4000-8000-000000000006',
    dealId: DEMO_DEAL_ID,
    family: 'WART_RESERVE',
    name: 'WART Covenant',
    description: 'Enhanced reserve if weighted average remaining lease term falls below 2.5 years.',
    metricKey: 'weightedAvgRemainingLeaseTerm',
    operator: 'LT',
    threshold: 2.5,
    thresholdUnit: 'years',
    lookbackPeriods: 1,
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.18',
    sourceText: 'Portfolio weighted average remaining lease term shall be maintained above 2.5 years.',
    extractionStatus: 'APPROVED',
    extractionConfidence: 0.89,
    watchBuffer: 0.1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '11111111-0000-4000-8000-000000000007',
    dealId: DEMO_DEAL_ID,
    family: 'EXPENSE_RESERVE',
    name: 'Operating Expense Reserve',
    description: 'Enhanced reserve if the operating expense reserve falls below $6.0M.',
    metricKey: 'expenseReserveBalance',
    operator: 'LT',
    threshold: 6_000_000,
    thresholdUnit: 'USD',
    lookbackPeriods: 1,
    consequence: 'ENHANCED_RESERVE',
    sectionReference: 'Section 3.19',
    sourceText: 'The issuer shall maintain an Operating Expense Reserve of at least $6,000,000 at all times.',
    extractionStatus: 'APPROVED',
    extractionConfidence: 0.9,
    watchBuffer: 0.1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: '11111111-0000-4000-8000-000000000008',
    dealId: DEMO_DEAL_ID,
    family: 'ARD_MATURITY',
    name: 'ARD Turbo Test',
    description: 'Turbo amortisation test tied to ARD maturity surveillance.',
    metricKey: 'dscr',
    operator: 'LT',
    threshold: 1,
    thresholdUnit: 'x',
    lookbackPeriods: 1,
    consequence: 'TURBO_AMORTISATION',
    sectionReference: 'Section 3.20',
    sourceText: 'Additional Notes may only be issued if DSCR pro forma is greater than or equal to 1.35x.',
    extractionStatus: 'APPROVED',
    extractionConfidence: 0.84,
    watchBuffer: 0.1,
    active: true,
    createdAt: now,
    updatedAt: now,
  },
]

const months = [
  ['2025-01-31', 0.87, 1.42, 0.59, 0.28, 3.2, 7_800_000],
  ['2025-02-28', 0.87, 1.41, 0.59, 0.28, 3.17, 7_600_000],
  ['2025-03-31', 0.86, 1.4, 0.6, 0.29, 3.13, 7_450_000],
  ['2025-04-30', 0.85, 1.38, 0.6, 0.29, 3.1, 7_300_000],
  ['2025-05-31', 0.83, 1.37, 0.6, 0.3, 3.06, 7_150_000],
  ['2025-06-30', 0.82, 1.36, 0.61, 0.3, 3.02, 7_050_000],
  ['2025-07-31', 0.8, 1.33, 0.61, 0.31, 2.98, 6_950_000],
  ['2025-08-31', 0.78, 1.32, 0.61, 0.31, 2.94, 6_850_000],
  ['2025-09-30', 0.76, 1.28, 0.62, 0.32, 2.9, 6_700_000],
  ['2025-10-31', 0.76, 1.19, 0.62, 0.32, 2.86, 6_850_000],
  ['2025-11-30', 0.76, 1.16, 0.62, 0.32, 2.83, 6_750_000],
  ['2025-12-31', 0.8, 1.14, 0.62, 0.32, 2.8, 6_700_000],
] as const

export const demoSnapshots: PerformanceSnapshot[] = months.map(
  ([periodDate, occupancyRate, dscr, ltv, topTenantRevenuePct, wart, reserve], index) => {
    const totalCapacityMW = 485
    const leasedCapacityMW = Math.round(totalCapacityMW * occupancyRate * 100) / 100
    const scheduledDebtService = 6_000_000
    const netCashFlow = Math.round(scheduledDebtService * dscr)

    return {
      id: `22222222-0000-4000-8000-${String(index + 1).padStart(12, '0')}`,
      dealId: DEMO_DEAL_ID,
      periodDate,
      occupancyRate,
      leasedCapacityMW,
      totalCapacityMW,
      contractedRevenue: 12_000_000 - index * 90_000,
      grossRevenue: 12_300_000 - index * 100_000,
      operatingExpenses: 4_000_000 + index * 35_000,
      netCashFlow,
      scheduledDebtService,
      seniorDebtService: 4_800_000,
      dscr,
      seniorDscr: Math.round((netCashFlow / 4_800_000) * 100) / 100,
      pueRatio: 1.25 + index * 0.003,
      powerCostPerKwh: 0.081 + index * 0.001,
      topTenantRevenuePct,
      tenantCount: 42 - Math.floor(index / 5),
      weightedAvgRemainingLeaseTerm: wart,
      outstandingBalance: 940_000_000 - index * 5_000_000,
      appraisedValue: Math.round((940_000_000 - index * 5_000_000) / ltv),
      ltv,
      seniorInterestReserveBalance: 20_000_000,
      expenseReserveBalance: reserve,
      requiredReserveBalance: 6_000_000,
      source: 'DEMO',
      notes: 'Synthetic Centersquare monthly surveillance scenario',
      createdAt: `${periodDate}T00:00:00.000Z`,
    }
  },
)

export function demoEvaluationsForSnapshot(snapshotId: string): TriggerEvaluation[] {
  const snapshot = demoSnapshots.find((item) => item.id === snapshotId) ?? demoSnapshots.at(-1)
  if (!snapshot) return []
  const scopedSnapshots = demoSnapshots.filter((item) => item.periodDate <= snapshot.periodDate)
  return evaluateAllTriggers(demoTriggerRules, scopedSnapshots)
}

export const demoEvaluations = demoSnapshots.flatMap((snapshot) =>
  demoEvaluationsForSnapshot(snapshot.id),
)

export function toDealRow(deal: Deal): Database['public']['Tables']['deals']['Insert'] {
  return {
    id: deal.id,
    user_id: deal.userId,
    name: deal.name,
    issuer: deal.issuer,
    closing_date: deal.closingDate,
    ar_date: deal.arDate,
    total_issuance: deal.totalIssuance,
    asset_count: deal.assetCount,
    collateral_description: deal.collateralDescription,
    rating_agency: deal.ratingAgency,
    rating: deal.rating,
    ltv: deal.ltv,
    is_demo: deal.isDemo,
    status: deal.status,
    created_at: deal.createdAt,
    updated_at: deal.updatedAt,
  }
}

export function toTriggerRuleRow(
  rule: TriggerRule,
): Database['public']['Tables']['trigger_rules']['Insert'] {
  return {
    id: rule.id,
    deal_id: rule.dealId,
    family: rule.family,
    name: rule.name,
    description: rule.description,
    metric_key: rule.metricKey,
    operator: rule.operator,
    threshold: rule.threshold,
    threshold_unit: rule.thresholdUnit,
    lookback_periods: rule.lookbackPeriods,
    consequence: rule.consequence,
    section_reference: rule.sectionReference,
    source_text: rule.sourceText,
    extraction_status: rule.extractionStatus,
    extraction_confidence: rule.extractionConfidence,
    watch_buffer: rule.watchBuffer,
    active: rule.active,
    created_at: rule.createdAt,
    updated_at: rule.updatedAt,
  }
}

export function toSnapshotRow(
  snapshot: PerformanceSnapshot,
): Database['public']['Tables']['performance_snapshots']['Insert'] {
  return {
    id: snapshot.id,
    deal_id: snapshot.dealId,
    period_date: snapshot.periodDate,
    occupancy_rate: snapshot.occupancyRate,
    leased_capacity_mw: snapshot.leasedCapacityMW,
    total_capacity_mw: snapshot.totalCapacityMW,
    contracted_revenue: snapshot.contractedRevenue,
    gross_revenue: snapshot.grossRevenue,
    operating_expenses: snapshot.operatingExpenses,
    net_cash_flow: snapshot.netCashFlow,
    scheduled_debt_service: snapshot.scheduledDebtService,
    senior_debt_service: snapshot.seniorDebtService,
    dscr: snapshot.dscr,
    senior_dscr: snapshot.seniorDscr,
    ltv: snapshot.ltv,
    pue_ratio: snapshot.pueRatio,
    power_cost_per_kwh: snapshot.powerCostPerKwh,
    top_tenant_revenue_pct: snapshot.topTenantRevenuePct,
    tenant_count: snapshot.tenantCount,
    weighted_avg_remaining_lease_term: snapshot.weightedAvgRemainingLeaseTerm,
    outstanding_balance: snapshot.outstandingBalance,
    appraised_value: snapshot.appraisedValue,
    senior_interest_reserve_balance: snapshot.seniorInterestReserveBalance,
    expense_reserve_balance: snapshot.expenseReserveBalance,
    required_reserve_balance: snapshot.requiredReserveBalance,
    source: snapshot.source,
    notes: snapshot.notes,
    created_at: snapshot.createdAt,
  }
}

export function toEvaluationRow(
  evaluation: TriggerEvaluation,
): Database['public']['Tables']['trigger_evaluations']['Insert'] {
  return {
    rule_id: evaluation.ruleId,
    snapshot_id: evaluation.snapshotId,
    status: evaluation.status,
    current_value: evaluation.currentValue,
    threshold: evaluation.threshold,
    distance_to_breach_pct: evaluation.distanceToBreachPct,
    lookback_values: evaluation.lookbackValues,
    evaluated_at: evaluation.evaluatedAt,
  }
}
